### PR TITLE
Support sending long data

### PR DESCRIPTION
**Pull request by Runc2333**
The ESP8266 module cannot send large TCP packets, and it will throw a `too long` error when you trying to.
By spliting data into small packet, we're able to send large TCP packets.

### CODE REVIEW

**Comment by Runc2333** [comment]
Sorry about the formatting issue, mainly rewrited the `write` function.

**Review by niklauslee — CHANGES_REQUESTED** [review]
Please keep the same format (2 spaces for indentation).

**Comment by Runc2333** [comment]
image
Tests are all passed.
But there's a one more problem, modern browsers will reuse the TCP tunnel by default, and this will cause the second request from the same browser fail.
By fixing this, I tried to close the connection everytime after the data was sent, but this causes the test failure, I'm not sure about if I should do this.

**Comment by niklauslee** [comment]
@Runc2333 Thank you for your contribution!

As mentioned in README, this is an experimental driver. While I implementing this driver, I feel that it is very difficult to implement fully operating TCP sockets based on AT command.

For now, it is more stable to use the AT command directly according to the use case rather than using the driver now.

**Pull request merged**
